name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Smoke tests - quick verification
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run smoke tests
        run: npm run test:smoke
        env:
          BASE_URL: ${{ secrets.BASE_URL || 'http://localhost:3000' }}
          API_URL: ${{ secrets.API_URL || 'http://localhost:3000/api' }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke-test-artifacts
          path: |
            cypress/screenshots
            cypress/videos

  # Full test suite
  e2e-tests:
    runs-on: ubuntu-latest
    needs: smoke-tests
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests on ${{ matrix.browser }}
        run: npm run test:${{ matrix.browser }}
        env:
          BASE_URL: ${{ secrets.BASE_URL || 'http://localhost:3000' }}
          API_URL: ${{ secrets.API_URL || 'http://localhost:3000/api' }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL || 'test@example.com' }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD || 'password123' }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-artifacts-${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos

  # Code quality checks
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

  # Environment-specific tests
  environment-tests:
    runs-on: ubuntu-latest
    needs: smoke-tests
    strategy:
      matrix:
        environment: [staging, production]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests on ${{ matrix.environment }}
        run: npm run test:${{ matrix.environment }}
        env:
          BASE_URL: ${{ secrets[format('{0}_URL', matrix.environment)] }}
          API_URL: ${{ secrets[format('{0}_API_URL', matrix.environment)] }}
          TEST_USER_EMAIL: ${{ secrets[format('{0}_TEST_USER_EMAIL', matrix.environment)] }}
          TEST_USER_PASSWORD: ${{ secrets[format('{0}_TEST_USER_PASSWORD', matrix.environment)] }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.environment }}-test-artifacts
          path: |
            cypress/screenshots
            cypress/videos